on:
  workflow_dispatch

name: pkgdown

jobs:
  pkgdown:

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-22.04, r: 'release', renv: '~/.local/share/renv'}

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_RENV_CACHE_DIR: ${{ matrix.config.renv }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::rcmdcheck
            any::knitr
            any::rmarkdown,
            any::testthat
            any::sessioninfo
            any::pkgdown
          needs: |
            website
            coverage

      - name: Pandoc setup
        uses: r-lib/actions/setup-pandoc@v2

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Install this (sfSpHelpers) package
        run: R CMD INSTALL .

      - name: Deploy new doc
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          Rscript -e 'pkgdown::build_site()'

      - name: Clean errors and artefacts
        run: |
          [ ! -f .github/depends.Rds ] || rm .github/depends.Rds
          [ ! -f .github/R-version ] || rm .github/R-version
          [ ! -f docs/pull_request_template.html ] || rm docs/pull_request_template.html

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update package documentation
          title: 'Package documentation'
          body: >
            This PR is auto-generated. Make sure all
            your changes are reflected in `docs/`
          labels: documentation, automated pr
