# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    if: ${{ contains(github.ref_name, 'create-pull-request/patch') }} == 'false' && github.actor != 'github-actions'

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-22.04, r: 'release', renv: '~/.local/share/renv'}

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GIT_HUB_PAT_SECRET }}
      R_RENV_CACHE_DIR: ${{ matrix.config.renv }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::ggplot2
            any::rcmdcheck
            any::sf
          needs: |
            website
            coverage

      - name: Pandoc setup
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies using renv
        run: |
          install.packages('renv')
          renv::activate()
          renv::restore()
        shell: Rscript {0}

      - name: Check (rcmdcheck should be in renv.lock)
        env:
          _R_CHECK_CRAN_INCOMING_: false
        run: |
          renv::restore()
          results = rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran", "--no-multiarch"), error_on = "error", check_dir = "check")
        shell: Rscript {0}
